In [6]:
class classroom:

SyntaxError: unexpected EOF while parsing (<ipython-input-6-6d0a3e8866a9>, line 1)

In [3]:
def test():
    print('test() for function')
    return
test()

test() for function


In [2]:
class demo:
    def test(self):
        print('test for class() and menthod')
        return
obj=demo()
obj.test()

test for class() and menthod


## factorial

In [14]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while (n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
p1.fact(5)

120

In [24]:
class demo2:
    def accept(self,p1,p2):
        self.a=p1
        self.b=p2
        return
    def display(self):
        print('a',a)
        print('b',b)
c1=demo2()
c1.accept(10,20)

In [25]:
class demo:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo(10,20)
print(c1.add(100,200))

300


In [1]:
class demo:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def mul(self,p1,p2):
        return p1*p2
c1=demo(10,20)
print(c1.mul(100,200))

20000


## double click to edit

In [11]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
class employee(person):
    def isemployee(person):
        return True


emp=person("chinmay")
print(emp.getname(),emp.isemployee())

emp=employee("rohan")
print(emp.getname(),emp.isemployee())

chinmay False
rohan True


In [8]:
lst=[1,2,3,4,5,6]
print(lst)

[1, 2, 3, 4, 5, 6]


In [12]:
import numpy as np
lst=[1,2,3,4]
a=np.array(lst)
print(a)


[1 2 3 4]


In [13]:
lst=[1,2,3,4]
a=np.array(lst)
print(a.shape)
print(a.dtype)

(4,)
int32


In [14]:
lst=[1,2,3,8.4]
a=np.array(lst)
print(a.shape)
print(a.dtype)

(4,)
float64


In [16]:
import numpy as np
a1=np.array([(1,2,3),(1,2,3)])
print(a1.shape)
a1=np.array([(1,2,3),(1,2,3),(1,2,3)])
print(a1.shape)

(2, 3)
(3, 3)


In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)



[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))


[[1 2 3]
 [4 5 6]]


In [17]:
import numpy as np
a1=np.random.normal(5,0.5,10)
print(a1)

[4.98829037 4.49197035 5.39637342 4.33181085 4.93009447 5.34054809
 4.84042695 4.52453414 4.64462717 6.36121297]


In [18]:
import numpy as np
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
import numpy as np
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [25]:
import numpy as np
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[1][3]=14
np.asarray(a)[3][3]=16
print(a)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [47]:
import numpy as np
a=np.matrix(np.ones((3,3),dtype=np.int64))
np.asarray(a)[0][0]=14
np.asarray(a)[2][2]=16
np.asarray(a)[1][1]=0````````````````````````
print(a)
print('sum=',np.asarray(a)[0][0]+np.asarray(a)[2][2]+np.asarray(a)[1][1])


[[14  1  1]
 [ 1  0  1]
 [ 1  1 16]]
sum= 30


In [36]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [41]:
np.arange(2,20,2)
np.arange(1,25,21)

array([ 1, 22])

In [48]:
a1=np.array([(1,2,3),(4,5,6)])
print('slicing colum:',a[:,2])

slicing colum: [[ 1]
 [ 1]
 [16]]


In [50]:
a1=np.array([(1,2,3),(4,5,6)])
print('slicing colum:',a[:,1])
print(a1[0])
print(a1[1])

slicing colum: [[1]
 [0]
 [1]]
[1 2 3]
[4 5 6]


In [52]:
a1=np.random.normal(5,1,10)
print(a1)
print('min val=',np.min(a1))
print('max val=',np.max(a1))
print('mean val=',np.mean(a1))
print('median val=',np.median(a1))

[5.29194319 5.01075075 5.29905922 5.13374411 5.33697618 6.66281887
 5.17018367 3.35896653 4.62580499 6.80290057]
min val= 3.3589665275267557
max val= 6.8029005732559495
mean val= 5.269314808260349
median val= 5.231063431854222


In [54]:
c1=np.array([1,2,2])
c2=np.array([4,5,7])
np.cross(c1,c2)

array([ 4,  1, -3])

In [56]:
c1=np.array([1,2,2])
c2=np.array([4,5,7])
np.dot(c1,c2)

28

In [58]:
c1=np.array([1,2,2])
c2=np.array([4,5,7])
c3=np.array([7,8,9])
np.matmul(c1,c2,c3)

array([28,  8,  9])